export default function TermsPage() {
  return (
    <div className="container">
      <h1>Terms of Service</h1>
      <p className="muted">Last updated: July 29, 2026</p>

      <p>
        These terms cover your use of AI Checker, the browser extension and website operated by
        us at werida.io. By creating an account or using the extension, you&apos;re agreeing to
        them. Please read through them once, they&apos;re short.
      </p>

      <h2>What AI Checker does</h2>
      <p>
        AI Checker gives you a prediction on whether a piece of text was written by a human or
        generated by AI. That prediction comes from Pangram, a third-party detection service we
        use under the hood. It&apos;s a strong signal, not a certainty, and it can be wrong. Please
        don&apos;t use a single AI Checker result as the sole basis for expelling a student, firing
        an employee, rejecting someone&apos;s work, or any other decision with serious consequences
        for a person. Use it as one input among several.
      </p>

      <h2>Who can use it</h2>
      <p>
        You need to be at least 16 years old to create an account. If you&apos;re using AI Checker
        on behalf of a school, company, or other organization, you&apos;re confirming you have the
        authority to agree to these terms for them.
      </p>
      <p>
        Keep your login credentials to yourself and let us know right away at{" "}
        <a href="mailto:support@werida.io">support@werida.io</a> if you think someone else has
        gotten into your account.
      </p>

      <h2>Plans, credits, and billing</h2>
      <p>
        Each plan comes with a set number of credits per month, and 1 credit covers roughly 1,000
        words of text checked. Unused credits don&apos;t carry over into the next month, whether
        you&apos;re on the Free plan or a paid one. You can see exactly what&apos;s included on the{" "}
        <a href="/pricing">pricing page</a>.
      </p>
      <p>
        Paid plans renew automatically each month and we&apos;ll charge whatever payment method
        you have on file through Stripe. If we ever change prices, we&apos;ll give you notice
        before it applies to you, and it won&apos;t change mid-cycle without warning.
      </p>

      <h2>Cancelling and refunds</h2>
      <p>
        You can cancel a paid plan any time from your dashboard under Manage billing. Cancelling
        doesn&apos;t cut you off right away: you keep the plan you paid for until the end of that
        billing period, and we won&apos;t charge you again after that. In other words, if you
        cancel on day 10 of a 30 day cycle, you still have Pro (or Business) access, credits and
        all, for the remaining 20 days.
      </p>
      <p>
        We don&apos;t give partial refunds for time you didn&apos;t use within a billing period.
        That said, if you were charged by mistake or something genuinely went wrong on our end,
        email <a href="mailto:support@werida.io">support@werida.io</a> and we&apos;ll sort it out.
        Refund requests outside of that are handled case by case, at our discretion.
      </p>
      <p>
        If a renewal payment fails, we don&apos;t cut you off immediately either. We&apos;ll retry
        the charge automatically over the next several days, and whatever credits you still have
        keep working in the meantime. You just won&apos;t get a fresh batch of credits until the
        payment actually goes through. If it never does, your account moves back to the Free plan.
      </p>

      <h2>Using AI Checker fairly</h2>
      <p>Please don&apos;t:</p>
      <ul>
        <li>Script or automate free-tier checks to get around the credit limits.</li>
        <li>Resell or redistribute access to the API or the detection results.</li>
        <li>Submit content you don&apos;t have the right to submit, or that violates someone else&apos;s rights.</li>
        <li>Try to reverse-engineer, scrape, or interfere with how the service works.</li>
      </ul>
      <p>
        If we see a pattern of abuse like this, we can suspend or close the account involved, with
        or without notice depending on how serious it is.
      </p>

      <h2>Your content</h2>
      <p>
        The text you submit for checking is yours. We only use it to run the detection and, if you
        choose to save it, to show it back to you in your history. We don&apos;t claim ownership
        over it and we don&apos;t use it for anything beyond providing you the service, see our{" "}
        <a href="/privacy">Privacy Policy</a> for the full picture of how that data is handled.
      </p>

      <h2>No warranties, and the boring liability part</h2>
      <p>
        AI Checker is provided as is. We work to keep it accurate and available, but we can&apos;t
        promise it&apos;ll be perfect, uninterrupted, or error-free, and we can&apos;t guarantee
        any particular detection result is correct.
      </p>
      <p>
        To the extent the law allows it, our liability to you for anything related to AI Checker
        is limited to whatever you&apos;ve paid us in the twelve months before the issue came up.
        We&apos;re not liable for indirect or consequential damages, like lost profits or lost
        data, arising from your use of the service.
      </p>

      <h2>Changes to the service or these terms</h2>
      <p>
        We&apos;re a small, evolving product, so features and limits may change as we go. If we
        make a significant change to these terms, we&apos;ll post the update here and change the
        date at the top. If you keep using AI Checker after that, it means you&apos;re fine with
        the new version.
      </p>

      <h2>Ending your account</h2>
      <p>
        You can close your account at any time from Account Settings. We can also suspend or close
        an account that breaks these terms, or that we reasonably believe is being used
        fraudulently or abusively.
      </p>

      <h2>Questions</h2>
      <p>
        Reach us any time at <a href="mailto:support@werida.io">support@werida.io</a>.
      </p>
    </div>
  );
}
