import type { Metadata } from "next";
import Link from "next/link";
import { CHROME_STORE_URL } from "@/lib/constants";

export const metadata: Metadata = {
  title: "Understanding your result - AI Checker",
  description:
    "A detailed, no-doubts walkthrough of every part of an AI Checker result: the verdict, the percentage, the AI/Assisted/Human breakdown, confidence, the positional bar, and the highlighted text.",
};

export default function ResultSupportPage() {
  return (
    <div className="container" style={{ paddingBottom: 64 }}>
      <h1>Understanding your result</h1>
      <p className="muted" style={{ maxWidth: 640 }}>
        Every part of a result screen means something specific. This page walks through each
        piece in order, top to bottom, so there&apos;s no ambiguity about what you&apos;re looking
        at or what to do next.
      </p>

      <nav className="support-jumpnav" aria-label="Jump to a section">
        <a href="#verdict">The verdict</a>
        <a href="#percentage">The percentage</a>
        <a href="#breakdown">AI / Assisted / Human</a>
        <a href="#confidence">Confidence</a>
        <a href="#positional-bar">Where in the text</a>
        <a href="#highlighted-text">Highlighted text</a>
        <a href="#what-to-do">What to do next</a>
        <a href="#limits">What this can&apos;t tell you</a>
      </nav>

      <div className="card" id="verdict">
        <h3>The verdict at the top</h3>
        <p>
          Every result starts with one sentence - something like{" "}
          <em>&quot;We believe that this text is fully human-written,&quot;</em>{" "}
          <em>&quot;We believe that this text is fully AI-generated,&quot;</em> or{" "}
          <em>&quot;We believe that this text is a mix of AI and human-written content.&quot;</em>
        </p>
        <p>
          This is deliberately worded to only say <strong>&quot;fully&quot;</strong> one way or
          the other when the evidence is genuinely overwhelming - not just when one category
          happens to be the largest. A document that&apos;s 55% human and 45% AI is a real mix,
          not &quot;mostly human&quot; - so it gets called a mix, not a fully-human verdict with an
          asterisk. If you ever see a percentage well above 0% sitting under a &quot;fully
          human-written&quot; verdict (or the reverse), that&apos;s worth reporting to us directly
          - <a href="mailto:support@werida.io">support@werida.io</a> - it means something looked
          wrong.
        </p>
      </div>

      <div className="card" id="percentage">
        <h3>The big percentage</h3>
        <p>
          The large number under the verdict (e.g. <strong>41%</strong>) is <em>&quot;of this
          text shows AI involvement&quot;</em> - it&apos;s the share of the actual words in your
          text that our model classified as AI-generated or AI-assisted, combined. It is{" "}
          <strong>not</strong> a probability that a human wrote the piece, and it&apos;s not a
          plagiarism score. It&apos;s a proportion: out of everything you submitted, this much of
          it reads as machine-influenced.
        </p>
        <p className="muted">
          A short document has fewer words to spread that percentage across, so a single AI-sounding
          sentence in a 60-word paragraph can swing the number more than the same sentence would in
          a 600-word one. Longer submissions generally give a more stable, more trustworthy
          percentage.
        </p>
      </div>

      <div className="card" id="breakdown">
        <h3>AI / Assisted / Human - the three categories</h3>
        <p>Every word in your text falls into exactly one of three buckets:</p>
        <ul style={{ paddingLeft: 20, lineHeight: 1.9 }}>
          <li>
            <strong style={{ color: "#c2410c" }}>AI</strong> - this stretch reads as generated by
            an AI model with no meaningful human authorship. Shown in red in the highlighted text
            view.
          </li>
          <li>
            <strong style={{ color: "#b45309" }}>Assisted</strong> - this stretch shows
            characteristics of both human and AI writing. Most often this means human-written text
            that was run through an AI tool to polish, rephrase, or extend it, or an AI draft that
            was substantially hand-edited afterward - the boundary between the two gets blurry
            enough that it&apos;s not confidently one or the other. Shown in yellow.
          </li>
          <li>
            <strong style={{ color: "#15803d" }}>Human</strong> - no meaningful AI involvement
            detected in this stretch. Left unhighlighted (plain text) in the highlighted text view,
            specifically so the parts that <em>are</em> flagged stand out clearly against everything
            that isn&apos;t.
          </li>
        </ul>
        <p className="muted">
          The three percentages under the breakdown bar (e.g. <em>AI 29% · Assisted 12% · Human
          59%</em>) always add up to 100% - together they account for every word in the text.
        </p>
      </div>

      <div className="card" id="confidence">
        <h3>The confidence badge</h3>
        <p>
          Next to the percentage, a small badge reads <strong>High</strong>,{" "}
          <strong>Medium</strong>, or <strong>Low</strong> confidence. This is a separate
          measurement from the percentage itself - it tells you how clear-cut the underlying
          scoring was for <em>this particular text</em>, not how much AI is in it.
        </p>
        <ul style={{ paddingLeft: 20, lineHeight: 1.9 }}>
          <li>
            <strong>High confidence</strong> - the model&apos;s scoring was decisive throughout;
            the result is unlikely to flip on a re-check of the same text.
          </li>
          <li>
            <strong>Medium confidence</strong> - some parts of the text scored closer to the
            boundary between categories. The overall verdict is still a reasonable read, but treat
            it as a somewhat softer signal.
          </li>
          <li>
            <strong>Low confidence</strong> - a meaningful portion of the text was genuinely
            ambiguous to the model. This can happen with short texts, very formal or
            old-fashioned-sounding prose, heavily quoted material, or text in an unusual style.
            Weigh a low-confidence result more lightly, and consider it alongside other context
            you have about where the text came from.
          </li>
        </ul>
      </div>

      <div className="card" id="positional-bar">
        <h3>Where in the text (the positional bar)</h3>
        <p>
          Below the breakdown, a sentence like <em>&quot;AI involvement is concentrated in the
          later part of this text&quot;</em> and a second, softer-colored bar show{" "}
          <strong>where</strong> in the document the AI/Assisted/Human stretches actually fall -
          left to right, matching the text&apos;s own reading order from start to end. Hover over
          any colored block to see its exact label and confidence.
        </p>
        <p className="muted">
          This bar is intentionally a different, paler color palette from the bold breakdown bar
          above it - the breakdown bar always reads AI→Assisted→Human by proportion, while this one
          reads by actual position in the text, which is very often a different order. They&apos;re
          answering two different questions (&quot;how much&quot; vs. &quot;where&quot;), not
          contradicting each other.
        </p>
      </div>

      <div className="card" id="highlighted-text">
        <h3>The highlighted text itself</h3>
        <p>
          The full text you submitted, with the exact stretches that scored AI or Assisted marked
          directly in red or yellow. This is the most precise view available - rather than a
          single number for the whole document, you can see <strong>exactly which sentences</strong>{" "}
          drove that number.
        </p>
        <p>
          In the extension, this view is collapsed behind a <strong>&quot;Show highlighted
          text&quot;</strong> toggle by default (the same text is already visible, editable, in the
          box below it) - click it to expand. On a shared result page it&apos;s shown directly.
        </p>
      </div>

      <div className="card" id="what-to-do">
        <h3>What to do with a mixed or AI-flagged result</h3>
        <p>
          If your goal is to move a result toward &quot;human-written&quot; - for a student
          revising an essay, or anyone wanting their own voice to come through clearly - the
          highlighted text view tells you exactly where to focus:
        </p>
        <ol style={{ paddingLeft: 20, lineHeight: 1.9 }}>
          <li>Expand the highlighted text and find the red and yellow stretches.</li>
          <li>
            Rewrite those specific sentences in your own words - don&apos;t just swap a few words
            for synonyms, actually re-draft the idea the way you&apos;d naturally say it.
          </li>
          <li>Leave the unhighlighted (human) parts alone - they&apos;re not the problem.</li>
          <li>Paste the revised text back in and check again.</li>
        </ol>
        <p className="muted">
          This is exactly why editing and re-checking both happen in the same panel, right next to
          each other, instead of being two separate steps.
        </p>
      </div>

      <div className="card" id="limits">
        <h3>What this result can&apos;t tell you</h3>
        <p>
          This is a strong statistical signal, not a certainty and not legal proof. It cannot tell
          you <em>which</em> AI tool (if any) was used, and it cannot distinguish &quot;written by
          AI&quot; from &quot;happens to read in a very formal or generic style&quot; with perfect
          reliability - unusually formal, repetitive, or old-fashioned human writing occasionally
          scores as more AI-like than it should, which is part of why the confidence badge exists.
          Treat every result as one input among several, especially for anything with real
          consequences for someone - grading, hiring, publishing decisions, and so on - rather than
          the sole basis for a decision.
        </p>
      </div>

      <div className="card" style={{ marginTop: 8 }}>
        <h3>Still have a question about a specific result?</h3>
        <p style={{ marginBottom: 12 }}>
          Email <a href="mailto:support@werida.io">support@werida.io</a> with a link to the
          result (use the Share button on your dashboard, or the shared link if you already have
          one) and we&apos;ll take a look. For everything else, see the main{" "}
          <Link href="/support">Support</Link> page.
        </p>
        <a className="cta-button" href={CHROME_STORE_URL} target="_blank" rel="noreferrer" style={{ marginTop: 0 }}>
          Add to Chrome - it&apos;s free
        </a>
      </div>
    </div>
  );
}
